HTTP_ERROR_MESSAGES = {
    500: ("UNKNOWN",),
    400: ("VALIDATION_ERROR", "VALIDATION_ERROR_MAIL", "VALIDATION_ERROR_PHONE",),
    401: ("UNAUTHORIZED", "CODE_EXPIRED", "CODE_INVALID"),
    403: ("FORBIDDEN", "DRIVER_PROFILE_NOT_APPROVED"),
    404: ("NOT_FOUND",),
    409: ("CONFLICT",),
    429: ("RATE_LIMIT_EXCEEDED",),
}