"""added middle_name, email, city, photo_url columns to user

Revision ID: 17b2bca1224f
Revises: f979e2435424
Create Date: 2025-12-30 11:52:05.328343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '17b2bca1224f'
down_revision: Union[str, None] = 'f979e2435424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'city')
    op.drop_column('users', 'email')
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###
