"""added currnet_class column for DriverProfile

Revision ID: 358d19947744
Revises: 43cc8eb652ff
Create Date: 2025-12-30 14:36:10.650534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358d19947744'
down_revision: Union[str, None] = '43cc8eb652ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('current_class', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_profiles', 'current_class')
 # ### end Alembic commands ###
