"""added tariff_plan

Revision ID: d474883cbcea
Revises: add_update_balance
Create Date: 2025-12-17 17:13:08.618634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd474883cbcea'
down_revision: Union[str, None] = 'add_update_balance'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('effective_from', sa.TIMESTAMP(), nullable=False),
    sa.Column('effective_to', sa.TIMESTAMP(), nullable=True),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('rate_per_meter', sa.Float(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('commission_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Добавляем колонку как nullable, затем заполняем значения по умолчанию, потом делаем NOT NULL
    op.add_column('rides', sa.Column('tariff_plan_id', sa.Integer(), nullable=True))
    
    # Создаем тариф по умолчанию, если его нет
    op.execute("""
        INSERT INTO tariff_plans (name, base_fare, rate_per_meter, multiplier, commission_percentage, effective_from, created_at)
        VALUES ('Default', 100.0, 5.0, 1.0, 10.0, NOW(), NOW())
        ON CONFLICT DO NOTHING
    """)
    
    # Обновляем существующие rides с тарифом по умолчанию
    op.execute("""
        UPDATE rides 
        SET tariff_plan_id = (SELECT id FROM tariff_plans WHERE name = 'Default' LIMIT 1)
        WHERE tariff_plan_id IS NULL
    """)
    
    # Теперь делаем колонку NOT NULL
    op.alter_column('rides', 'tariff_plan_id', nullable=False)
    
    op.create_foreign_key(None, 'rides', 'tariff_plans', ['tariff_plan_id'], ['id'])
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'user_phone_number')
    op.drop_column('users', 'inviter_id')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'balance')
    op.drop_column('users', 'lang_code')
    op.drop_column('users', 'balance_updated_at')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('balance_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('lang_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('inviter_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_column('users', 'last_name')
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.drop_column('rides', 'tariff_plan_id')
    op.drop_table('tariff_plans')
    # ### end Alembic commands ###
