"""added ride_count column to DriverProfile

Revision ID: 43cc8eb652ff
Revises: 31ad96c64478
Create Date: 2025-12-30 13:45:16.071389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '43cc8eb652ff'
down_revision: Union[str, None] = '31ad96c64478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('ride_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_profiles', 'ride_count')
 # ### end Alembic commands ###
