"""added not-null constraint to role_id (User)

Revision ID: 31ad96c64478
Revises: 17b2bca1224f
Create Date: 2025-12-30 13:17:14.467798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '31ad96c64478'
down_revision: Union[str, None] = '17b2bca1224f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
 # ### end Alembic commands ###
