"""added is_registred column to phone_verification

Revision ID: f979e2435424
Revises: 503fad72d676
Create Date: 2025-12-27 10:53:20.745651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f979e2435424'
down_revision: Union[str, None] = '503fad72d676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_verifications', sa.Column('is_registred', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_verifications', 'is_registred')
    # ### end Alembic commands ###
