"""replaced display_anme with middle_name

Revision ID: 90c06136ceca
Revises: e5bb96387988
Create Date: 2026-01-21 13:49:23.982980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c06136ceca'
down_revision: Union[str, None] = 'e5bb96387988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.drop_column('driver_profiles', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('display_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('driver_profiles', 'middle_name')
    # ### end Alembic commands ###
