"""removed driver_fare column

Revision ID: bcf980727905
Revises: 6a82b2cffe25
Create Date: 2026-02-23 11:59:12.352242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf980727905'
down_revision: Union[str, None] = '6a82b2cffe25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'driver_fare')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('driver_fare', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
