"""changed eta type to JSONB

Revision ID: 59b41fcb7942
Revises: e38f0f51525a
Create Date: 2026-02-13 11:22:49.847802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59b41fcb7942'
down_revision: Union[str, None] = 'e38f0f51525a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ride_drivers_requests', 'eta',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='to_jsonb(eta)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ride_drivers_requests', 'eta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=50),
               postgresql_using='eta::varchar',
               existing_nullable=True)
    # ### end Alembic commands ###
