"""added delivery_receiver_name and delivery_receiver_phone columns

Revision ID: 18b1869f42b2
Revises: 11e4c4bca11a
Create Date: 2026-03-22 12:16:58.144940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b1869f42b2'
down_revision: Union[str, None] = '11e4c4bca11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('delivery_receiver_name', sa.String(length=100), nullable=True))
    op.add_column('rides', sa.Column('delivery_receiver_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'delivery_receiver_phone')
    op.drop_column('rides', 'delivery_receiver_name')
    # ### end Alembic commands ###
