"""added commission_paid_at column

Revision ID: d2c5617aa43b
Revises: 663cfc5acef4
Create Date: 2026-03-11 10:59:03.137620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c5617aa43b'
down_revision: Union[str, None] = '663cfc5acef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('commission_paid_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'commission_paid_at')
    # ### end Alembic commands ###
