"""removed unique constraint from tochka_operation_id

Revision ID: e5bb96387988
Revises: 33c91d8596f1
Create Date: 2026-01-17 19:00:24.414237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5bb96387988'
down_revision: Union[str, None] = '33c91d8596f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('commission_payments_tochka_operation_id_key'), 'commission_payments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('commission_payments_tochka_operation_id_key'), 'commission_payments', ['tochka_operation_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
