"""added driver_moderation_info and driver_profile_moderation

Revision ID: e292dbf0a08b
Revises: 3cb477f464a0
Create Date: 2026-03-23 16:10:52.942150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e292dbf0a08b'
down_revision: Union[str, None] = '3cb477f464a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_moderation_info',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_profile_moderation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('driver_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('driver_moderation_info_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_moderation_info_id'], ['driver_moderation_info.id'], ),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
        INSERT INTO driver_moderation_info (code, message) 
        VALUES 
            ('WAITING_MODERATION_PASSPORT', 'Waiting for passport approval'),
            ('WAITING_MODERATION_DRIVING_LICENSE', 'Waiting for driving license approval'),
            ('WAITING_MODERATION_STS', 'Waiting for STS approval'),
            ('WAITING_MODERATION_CAR', 'Waiting for car approval'),
            ('WAITING_MODERATION_INFO', 'Waiting for additional info approval')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_profile_moderation')
    op.drop_table('driver_moderation_info')
    # ### end Alembic commands ###
