"""deleted is_registred column

Revision ID: 431dd2161660
Revises: 2c8feaabb14f
Create Date: 2026-03-25 15:56:53.697981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431dd2161660'
down_revision: Union[str, None] = '2c8feaabb14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_verifications', 'is_registred')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_verifications', sa.Column('is_registred', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
