"""added distance_str and duration_str

Revision ID: b36f007ccea4
Revises: 42941395ff9d
Create Date: 2026-01-12 18:42:53.909016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b36f007ccea4'
down_revision: Union[str, None] = '42941395ff9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('distance_str', sa.String(length=50), nullable=True))
    op.add_column('rides', sa.Column('duration_str', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'duration_str')
    op.drop_column('rides', 'distance_str')
# ### end Alembic commands ###
