"""added not-null constraint for pickup_lat and pickup_lng

Revision ID: 192d5ea06bc3
Revises: bba4f3f90974
Create Date: 2026-01-06 14:33:28.584552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '192d5ea06bc3'
down_revision: Union[str, None] = 'bba4f3f90974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'pickup_lat',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               nullable=False)
    op.alter_column('rides', 'pickup_lng',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'pickup_lng',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               nullable=True)
    op.alter_column('rides', 'pickup_lat',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               nullable=True)
    # ### end Alembic commands ###
