"""added ride_type column

Revision ID: 24c187b46c4c
Revises: 3feab1f4d374
Create Date: 2026-01-31 14:15:03.651159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c187b46c4c'
down_revision: Union[str, None] = '3feab1f4d374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('ride_type', sa.Text(), nullable=False, server_default="with_car"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'ride_type')
    # ### end Alembic commands ###
