"""changed file_url column with file_bucket_key column

Revision ID: 2c8feaabb14f
Revises: e292dbf0a08b
Create Date: 2026-03-24 21:31:20.646338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8feaabb14f'
down_revision: Union[str, None] = 'e292dbf0a08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_documents', sa.Column('file_bucket_key', sa.String(), nullable=True))
    op.drop_column('driver_documents', 'file_url')
    op.add_column('car_photos', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_photos', 'status')
    op.add_column('driver_documents', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('driver_documents', 'file_bucket_key')
    # ### end Alembic commands ###
