"""added current_car_id column

Revision ID: 21ccce71f3b8
Revises: c059c42cd106
Create Date: 2026-01-29 15:25:01.474353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ccce71f3b8'
down_revision: Union[str, None] = 'c059c42cd106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('current_car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'driver_profiles', 'cars', ['current_car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver_profiles', type_='foreignkey')
    op.drop_column('driver_profiles', 'current_car_id')
    # ### end Alembic commands ###
