"""added eta column

Revision ID: 00c864c6eb4d
Revises: ee5ef61cb32e
Create Date: 2026-01-17 12:27:49.387060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c864c6eb4d'
down_revision: Union[str, None] = 'ee5ef61cb32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_drivers_requests', sa.Column('eta', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride_drivers_requests', 'eta')
    # ### end Alembic commands ###
