"""updated client_id constraint

Revision ID: 71daa819b571
Revises: b2c3d4e5f6a7
Create Date: 2026-05-26 21:41:30.397976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71daa819b571'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'client_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'client_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
