"""added offer_fare column

Revision ID: 7e8dc4efe007
Revises: bcf980727905
Create Date: 2026-03-03 16:25:26.524347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8dc4efe007'
down_revision: Union[str, None] = 'bcf980727905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_drivers_requests', sa.Column('offer_fare', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.drop_constraint(op.f('rides_tariff_plan_id_fkey'), 'rides', type_='foreignkey')
    op.drop_column('rides', 'tariff_plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride_drivers_requests', 'offer_fare')
    op.add_column('rides', sa.Column('tariff_plan_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('rides_tariff_plan_id_fkey'), 'rides', 'tariff_plans', ['tariff_plan_id'], ['id'])
    # ### end Alembic commands ###
