"""fixed rating_avg column

Revision ID: 7762dfef1dd6
Revises: d12c5f391cc6
Create Date: 2026-02-03 14:52:02.185839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7762dfef1dd6'
down_revision: Union[str, None] = 'd12c5f391cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver_profiles', 'rating_avg',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=3, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver_profiles', 'rating_avg',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
