"""added next_sending_at column

Revision ID: 6a82b2cffe25
Revises: 59b41fcb7942
Create Date: 2026-02-19 12:40:41.111150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a82b2cffe25'
down_revision: Union[str, None] = '59b41fcb7942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_verifications', sa.Column('next_sending_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_verifications', 'next_sending_at')
    # ### end Alembic commands ###
