"""added status for driver_profiles

Revision ID: 3cb477f464a0
Revises: ec65176aefab
Create Date: 2026-03-23 12:08:43.726814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb477f464a0'
down_revision: Union[str, None] = 'ec65176aefab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('status', sa.String(length=50), nullable=True))
    op.execute("UPDATE driver_profiles SET status = 'waiting_approved'")
    op.alter_column('driver_profiles', 'status', nullable=False)
    op.drop_column('driver_profiles', 'documents_status')
    op.drop_column('driver_profiles', 'documents_review_notes')
    op.drop_column('driver_profiles', 'qualification_level')
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('driver_profiles', sa.Column('qualification_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('driver_profiles', sa.Column('documents_review_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('driver_profiles', sa.Column('documents_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('driver_profiles', 'status')
    # ### end Alembic commands ###
