"""deleted raw_response and raw_request columns

Revision ID: 9be2a518e088
Revises: 24c187b46c4c
Create Date: 2026-01-31 15:19:35.833196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9be2a518e088'
down_revision: Union[str, None] = '24c187b46c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commission_payments', 'raw_request')
    op.drop_column('commission_payments', 'raw_response')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_payments', sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('commission_payments', sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
