"""deleted commission_percentage column

Revision ID: ec9f088cbc8e
Revises: 9f3a7d2c1b4e
Create Date: 2026-01-09 12:59:55.367693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec9f088cbc8e'
down_revision: Union[str, None] = '9f3a7d2c1b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariff_plans', 'commission_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff_plans', sa.Column('commission_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
