"""added commission_amount column

Revision ID: 663cfc5acef4
Revises: 7e8dc4efe007
Create Date: 2026-03-04 16:58:27.822934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '663cfc5acef4'
down_revision: Union[str, None] = '7e8dc4efe007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_drivers_requests', sa.Column('commission_amount', sa.DECIMAL(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride_drivers_requests', 'commission_amount')
    # ### end Alembic commands ###
