"""added read_at

Revision ID: be29bb34ea73
Revises: 7a4edf30151e
Create Date: 2026-01-10 20:57:37.399262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be29bb34ea73'
down_revision: Union[str, None] = '7a4edf30151e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('in_app_notifications', sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('in_app_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('in_app_notifications', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('in_app_notifications', 'read_at')
    # ### end Alembic commands ###
