"""removed accuracy_m and provider columns

Revision ID: 5b2a2b2fee49
Revises: 9be2a518e088
Create Date: 2026-02-01 16:59:53.039551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5b2a2b2fee49'
down_revision: Union[str, None] = '9be2a518e088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_locations', 'provider')
    op.drop_column('driver_locations', 'accuracy_m')
    op.drop_column('rides', 'ride_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_locations', sa.Column('accuracy_m', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('driver_locations', sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('rides', sa.Column('ride_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###
