"""added columns to car

Revision ID: d12c5f391cc6
Revises: 5b2a2b2fee49
Create Date: 2026-02-02 14:22:45.134062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12c5f391cc6'
down_revision: Union[str, None] = '5b2a2b2fee49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('region', sa.String(length=20), nullable=True, server_default=""))
    op.add_column('cars', sa.Column('vin', sa.String(length=100), nullable=True, server_default=""))
    op.add_column('cars', sa.Column('year', sa.String(length=10), nullable=True, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'year')
    op.drop_column('cars', 'vin')
    op.drop_column('cars', 'region')
    # ### end Alembic commands ###
