"""added dedup_key column

Revision ID: 42941395ff9d
Revises: be29bb34ea73
Create Date: 2026-01-12 14:27:25.780498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42941395ff9d'
down_revision: Union[str, None] = 'be29bb34ea73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('in_app_notifications', sa.Column('dedup_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('in_app_notifications', 'dedup_key')
# ### end Alembic commands ###
