"""changed is_online column to status column

Revision ID: 90d42639d5a1
Revises: 192d5ea06bc3
Create Date: 2026-01-08 11:37:35.550949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90d42639d5a1'
down_revision: Union[str, None] = '192d5ea06bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_locations', sa.Column('status', sa.String(length=50), nullable=True))
    op.execute("UPDATE driver_locations SET status = 'offline'")
    op.alter_column('driver_locations', 'status', nullable=False)
    op.drop_column('driver_locations', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_locations', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.execute("UPDATE driver_locations SET is_online = false")
    op.alter_column('driver_locations', 'is_online', nullable=False)
    op.drop_column('driver_locations', 'status')
    
    # ### end Alembic commands ###
