"""deleted transaction schema

Revision ID: e8c2d30edd24
Revises: 7762dfef1dd6
Create Date: 2026-02-05 15:51:01.241536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8c2d30edd24'
down_revision: Union[str, None] = '7762dfef1dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_column('commission_payments', 'transaction_id')
    op.drop_constraint(op.f('rides_transaction_id_fkey'), 'rides', type_='foreignkey')
    op.drop_column('rides', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('rides_transaction_id_fkey'), 'rides', 'transactions', ['transaction_id'], ['id'])
    op.add_column('commission_payments', sa.Column('transaction_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_withdraw', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('transactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    # ### end Alembic commands ###
