"""added commission_amount column

Revision ID: 33c91d8596f1
Revises: 00c864c6eb4d
Create Date: 2026-01-17 18:33:19.018722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c91d8596f1'
down_revision: Union[str, None] = '00c864c6eb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('commission_amount', sa.DECIMAL(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'commission_amount')
    # ### end Alembic commands ###
