"""harden push token ownership and admin duplicate protection

Revision ID: c4d5e6f7a8b9
Revises: b3c4d5e6f7a8
"""

from typing import Union

import sqlalchemy as sa
from alembic import op


revision: str = "c4d5e6f7a8b9"
down_revision: Union[str, None] = "b3c4d5e6f7a8"
branch_labels: Union[str, tuple[str, ...], None] = None
depends_on: Union[str, tuple[str, ...], None] = None


def upgrade() -> None:
    op.execute("UPDATE device_tokens SET platform = lower(trim(platform))")
    # Rank only valid registrations so an invalid newer duplicate cannot evict
    # the latest usable registration of the same token.
    op.execute(
        "WITH ranked AS ("
        "  SELECT id, row_number() OVER ("
        "    PARTITION BY token "
        "    ORDER BY created_at DESC NULLS LAST, id DESC"
        "  ) AS row_num "
        "  FROM device_tokens "
        "  WHERE platform IN ('android', 'ios')"
        ") "
        "DELETE FROM device_tokens AS candidate "
        "WHERE candidate.platform IS NULL "
        "   OR candidate.platform NOT IN ('android', 'ios') "
        "   OR EXISTS ("
        "     SELECT 1 FROM ranked "
        "     WHERE ranked.id = candidate.id AND ranked.row_num > 1"
        "   )"
    )
    op.execute("UPDATE device_tokens SET created_at = now() WHERE created_at IS NULL")
    op.alter_column(
        "device_tokens",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.create_unique_constraint("uq_device_tokens_token", "device_tokens", ["token"])
    op.create_check_constraint(
        "ck_device_tokens_platform",
        "device_tokens",
        "platform IN ('android', 'ios')",
    )

    op.add_column(
        "admin_push_notifications",
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
    )
    # Historical rows need a value for the non-null invariant. New rows use the
    # normalized SHA-256 fingerprint generated by the application.
    op.execute(
        "UPDATE admin_push_notifications SET fingerprint = "
        "repeat(md5(id::text || ':' || created_at::text), 2)"
    )
    op.alter_column("admin_push_notifications", "fingerprint", nullable=False)
    op.create_index(
        "ix_admin_push_notifications_fingerprint_created_at",
        "admin_push_notifications",
        ["fingerprint", "created_at"],
    )
    op.drop_constraint("ck_admin_push_status", "admin_push_notifications", type_="check")
    op.create_check_constraint(
        "ck_admin_push_status",
        "admin_push_notifications",
        "status IN ('processing', 'sent', 'partial', 'failed', 'unknown')",
    )


def downgrade() -> None:
    op.execute(
        "UPDATE admin_push_notifications SET status = 'failed' WHERE status = 'unknown'"
    )
    op.drop_constraint("ck_admin_push_status", "admin_push_notifications", type_="check")
    op.create_check_constraint(
        "ck_admin_push_status",
        "admin_push_notifications",
        "status IN ('processing', 'sent', 'partial', 'failed')",
    )
    op.drop_index(
        "ix_admin_push_notifications_fingerprint_created_at",
        table_name="admin_push_notifications",
    )
    op.drop_column("admin_push_notifications", "fingerprint")
    op.drop_constraint("ck_device_tokens_platform", "device_tokens", type_="check")
    op.drop_constraint("uq_device_tokens_token", "device_tokens", type_="unique")
    op.alter_column(
        "device_tokens",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=True,
    )
