"""added car_id column

Revision ID: c059c42cd106
Revises: 25a8c4e2c75d
Create Date: 2026-01-21 14:44:48.629998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c059c42cd106'
down_revision: Union[str, None] = '25a8c4e2c75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_drivers_requests', sa.Column('car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ride_drivers_requests', 'cars', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ride_drivers_requests', type_='foreignkey')
    op.drop_column('ride_drivers_requests', 'car_id')
    # ### end Alembic commands ###
