services:
  fastapi_app:
    env_file:
      - .env
    ports:
      - "8934:5000"
    volumes:
      - /www/u-bro.ru/staticfiles:/app/staticfiles

  db:
    env_file:
      - .env
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/db-files
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./logs/postgres-prod:/var/log/postgresql

  migration:
    env_file:
      - .env

  admin_service:
    env_file:
      - .env
    ports:
      - "3813:8000"
