name: Deploy-dev

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/deploy-dev/ubro_backend
          git checkout dev
          git pull origin dev
          cd Backend-Bot-master/
          docker compose -p ubro-dev -f docker-compose.yml -f docker-compose.dev.yml up -d --build
